(G-CODE GENERATED BY FLATCAM v8.994 - www.flatcam.org - Version Date: 2020/11/7)

(Name: Drill_NPTH_Through.DRL_cnc)
(Type: G-code from Geometry)
(Units: MM)

(Created on Sunday, 15 February 2026 at 21:42)

(This preprocessor is used with a motion controller loaded with GRBL firmware.)
(It is configured to be compatible with almost any version of GRBL firmware.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 2.032)
(Tool: 2 -> Dia: 3.0)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300)
(Tool: 2 -> Feedrate: 300)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)
(Tool: 2 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -2.0)
(Tool: 2 -> Z_Cut: -2.0)

(Tools Offset: )
(Tool: 1 -> Offset Z: 0.0)
(Tool: 2 -> Offset Z: 0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)
(Tool: 2 -> Z_Move: 2)

(Z Toolchange: 15 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 0.5 mm)
(X,Y End: None mm)
(Steps per circle: 64)
(Steps per circle: 64)
(Preprocessor Excellon: grbl_11)

(X range:    1.6417 ...  127.0227  mm)
(Y range:  -80.7530 ...   -3.3080  mm)

(Spindle Speed: 1000 RPM)
G21
G90
G17
G94


G01 F300.00

M5             
G00 Z15.0000
G00 X0.0000 Y0.0000                
T1

(MSG, Change to Tool Dia = 2.0320 ||| Total drills for tool T1 = 6)

G00 Z15.0000

G01 F300.00
M03 S1000
G00 X2.6577 Y-79.7370
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X2.6577 Y-56.7370
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X22.5227 Y-47.8080
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X22.5227 Y-4.8080
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X125.5227 Y-4.8080
G01 Z-2.0000
G01 Z0
G00 Z2.0000
G00 X125.5227 Y-47.8080
G01 Z-2.0000
G01 Z0
G00 Z2.0000
M05
G00 Z0.50


